name: odoo-crm
region: fra

databases:
  - name: odoo-postgres
    engine: PG
    version: "15"
    size: basic
    num_nodes: 1

services:
  - name: odoo
    source_dir: /
    github:
      repo: votre-username/odoo-crm
      branch: main
    dockerfile_path: Dockerfile
    
    instance_size_slug: basic-xxs
    instance_count: 1
    
    http_port: 8069
    
    health_check:
      http_path: /web/health
      initial_delay_seconds: 180
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: PORT
        value: "8069"
      - key: DATABASE_HOST
        value: ${odoo-postgres.HOSTNAME}
      - key: DATABASE_PORT
        value: ${odoo-postgres.PORT}
      - key: DATABASE_USER
        value: ${odoo-postgres.USERNAME}
      - key: DATABASE_PASSWORD
        value: ${odoo-postgres.PASSWORD}
      - key: DATABASE_NAME
        value: ${odoo-postgres.DATABASE}
      - key: ADMIN_PASSWORD
        value: "admin123"
      - key: ODOO_RC
        value: "/etc/odoo/odoo.conf"
    
    alerts:
      - rule: CPU_UTILIZATION
        value: 80
      - rule: MEM_UTILIZATION
        value: 80
      - rule: RESTART_COUNT
        value: 3