#!/bin/bash

echo "🚀 Guide de déploiement d'Odoo CRM"
echo "=================================="
echo ""
echo "📋 Étapes de déploiement :"
echo ""
echo "1. Assurez-vous que Docker est installé et en cours d'exécution :"
echo "   sudo systemctl start docker"
echo "   # ou"
echo "   sudo service docker start"
echo "   # ou"
echo "   sudo dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376 &"
echo ""
echo "2. Vérifiez que Docker fonctionne :"
echo "   docker version"
echo ""
echo "3. Démarrez les services Odoo :"
echo "   docker-compose up -d"
echo ""
echo "4. Vérifiez que les services sont en cours d'exécution :"
echo "   docker-compose ps"
echo ""
echo "5. Suivez les logs de démarrage :"
echo "   docker-compose logs -f"
echo ""
echo "🌐 Une fois démarré, accédez à :"
echo "   http://localhost:8069"
echo ""
echo "📊 Informations de connexion :"
echo "   Database: odoo"
echo "   User: admin"
echo "   Password: admin"
echo ""
echo "📝 Commandes utiles :"
echo "   docker-compose ps          # Voir le statut"
echo "   docker-compose logs -f     # Voir les logs"
echo "   docker-compose down        # Arrêter"
echo "   docker-compose restart     # Redémarrer"
echo ""
echo "🔧 En cas de problème :"
echo "   docker-compose down -v     # Supprimer les données"
echo "   docker-compose up -d       # Redémarrer proprement"